In [5]:
import pandas as pd
import seaborn as sns 
import plotly.express as px
import matplotlib.pyplot as plt
import numpy as np

## Analyse saisonnalité diagnostic toute pathologie

In [6]:
df_clinique = pd.read_csv("Resultats/Excels/patients_FR_geocoded_adultes_clinique.csv",sep=";", dtype={"codepost":str}, parse_dates=["date_diag"])
df_clinique['year'] = df_clinique["date_diag"].dt.year
df_clinique['month'] = df_clinique["date_diag"].dt.month

In [7]:
df_clinique = df_clinique[["pseudo_provisoire","year","month"]]
df_clinique

       pseudo_provisoire  year  month
0                      1  2018      4
1                      2  2017      7
2                      3  2019      1
3                      4  2019      6
4                      5  2018      2
...                  ...   ...    ...
57873              64290  2015      6
57874              64291  2015      6
57875              64292  1998      6
57876              64293  2000     11
57877              64294  2014     10

[57878 rows x 3 columns]

In [8]:

df_clinique_trunc = df_clinique.groupby(['year','month']).count().reset_index()

df_clinique_trunc = df_clinique_trunc.sort_values(by=['year','month'])

df_clinique_trunc["month_name"] = df_clinique_trunc['month'].apply(lambda x: pd.to_datetime(x,format='%m').month_name())

df_clinique_trunc = df_clinique_trunc[["year","month_name","pseudo_provisoire"]]

df_clinique_trunc = df_clinique_trunc.rename({'pseudo_provisoire':'count'},axis=1)
# df_clinique_trunc

In [9]:
df_clinique_trunc[df_clinique_trunc['year']>=2017]

     year month_name  count
504  2017    January    517
505  2017   February    423
506  2017      March    559
507  2017      April    416
508  2017        May    429
..    ...        ...    ...
574  2022   November      4
575  2022   December      6
576  2023    January      8
577  2023   February      3
578  2023      March      2

[75 rows x 3 columns]

In [10]:
df_clinique_trunc = df_clinique_trunc.iloc[504:]

# Création du graphique
fig = px.line(df_clinique_trunc, x='month_name', y='count', color='year',
              labels={'count':'Nombre d\'hospitalisations', 'month_name':'Mois', 'year':'Année'},
              title='Analyse saisonnière des dates de diagnostic par année')

fig.update_xaxes(categoryorder='array', categoryarray= [pd.to_datetime(x, format='%B').month_name() for x in pd.date_range('2020-01-01', periods=12, freq='M').month_name()])
fig.update_layout(xaxis_title='Mois', yaxis_title='Nombre d\'hospitalisations', legend_title='Année')
fig.show()

C:\Users\lpokambo\AppData\Local\Temp\ipykernel_8516\832644671.py:8: FutureWarning:

'M' is deprecated and will be removed in a future version, please use 'ME' instead.

## Analyse saisonnalité evenements médicaux

In [11]:
df_ap = pd.read_excel("../geocodeur/from_hegp/data/data_octobre_2023/medical_event/aplasie.xlsx", parse_dates=True)

In [12]:
df_ap['year'] = df_ap["Date début hospitalisation"].dt.year
df_ap['month'] = df_ap["Date début hospitalisation"].dt.month
df_ap['periode'] = df_ap["Date fin hospitalisation"] - df_ap["Date début hospitalisation"]

df_ap_yrs = df_ap.groupby(['year','month']).count().reset_index()
df_ap_yrs = df_ap_yrs.iloc[1:]

df_ap_yrs = df_ap_yrs.sort_values(by=['year','month'])

df_ap_yrs["month_name"] = df_ap_yrs['month'].apply(lambda x: pd.to_datetime(x,format='%m').month_name())

df_ap_yrs_truncated = df_ap_yrs[["year","month_name","pseudo_provisoire"]]

df_ap_yrs_truncated = df_ap_yrs_truncated.rename({'pseudo_provisoire':'count'},axis=1)

### Analyse de la saisonnalité - par année :

In [13]:
# Création du graphique
fig = px.line(df_ap_yrs_truncated, x='month_name', y='count', color='year',
              labels={'count':'Nombre d\'hospitalisations', 'month_name':'Mois', 'year':'Année'},
              title='Analyse saisonnière des hospitalisations pour aplasie par année')

fig.update_xaxes(categoryorder='array', categoryarray= [pd.to_datetime(x, format='%B').month_name() for x in pd.date_range('2020-01-01', periods=12, freq='M').month_name()])
fig.update_layout(xaxis_title='Mois', yaxis_title='Nombre d\'hospitalisations', legend_title='Année')
fig.show()

C:\Users\lpokambo\AppData\Local\Temp\ipykernel_8516\4068802645.py:6: FutureWarning:

'M' is deprecated and will be removed in a future version, please use 'ME' instead.