In [32]:
import pandas as pd
import psycopg2
import pandas as pd
import geopandas as gpd
import requests
from geopandas.tools import sjoin
import time
import datetime
from collections import Counter 
import re
import random
import numpy as np
import unidecode
import matplotlib.pyplot as plt
import plotly.graph_objects as go 
import plotly.express as px

In [33]:
df_position_bruit = pd.read_csv("data_with_biais/positon_bruit.csv",sep=";")

In [34]:
df_position_bruit["pos_bruit"] = df_position_bruit["pos_bruit"].str.replace("[",'')
df_position_bruit["pos_bruit"] = df_position_bruit["pos_bruit"].str.replace("]",'')
df_position_bruit["pos_bruit"] = df_position_bruit["pos_bruit"].astype(str)

In [46]:
df_position_bruit.loc[627,:]

Unnamed: 0                                                         8885
pseudo_provisoire                                                  8886
adresse               CHEZ MME MANCIEN                   30 BD MAL J...
codepost                                                        21000.0
nom_commune_postal                                                DIJON
bruit                                                 CHEZ,MME,BAT,APPT
pos_bruit                                                   1, 2, 8, 11
Name: 627, dtype: object

In [45]:
L = []

for i in df_position_bruit.index:
    s = len(df_position_bruit.loc[i,"pos_bruit"].split(","))
    if s >3:
        print(i)
    L.append(s)

print(np.mean(L))

627
991
1581
2448
3300
3679
3962
5329
1.2402892214561965

In [47]:
df_position_bruit[['bruit_1', 'bruit_2','bruit_3','bruit_4']] = df_position_bruit['pos_bruit'].str.split(', ', expand=True)

In [48]:
df_position_bruit.head()

,Unnamed: 0,pseudo_provisoire,adresse,codepost,nom_commune_postal,bruit,pos_bruit,bruit_1,bruit_2,bruit_3,bruit_4
0,15,16,CHEZ MR LARBI BOUABDALLAH 43 RUE DURI...,75020.0,PARIS,"CHEZ,MR","1, 2",1,2,None,None
1,34,35,17 RUE DE LA PROCESSION BAT 1 APPT ...,93250.0,VILLEMOMBLE,"BAT,APPT","6, 8",6,8,None,None
2,53,54,93 BD D'AULNAY RESIDENCE L...,93250.0,VILLEMONBLE,"RESIDENCE,BAT","4, 7",4,7,None,None
3,87,88,175 BVD DES PROVINCES FRANCAISE N22 APPT 50...,92000.0,NANTERRE,APPT,7,7,None,None,None
4,100,101,46 RUE PARJOT MAISON NUME...,49300.0,CHOLET,MAISON,4,4,None,None,None

In [49]:
df_position_bruit[df_position_bruit["bruit_1"]==""] = np.nan

df_position_bruit["bruit_1"] = df_position_bruit["bruit_1"].astype(float)

df_position_bruit[df_position_bruit["bruit_2"]==""] = np.nan

df_position_bruit["bruit_2"] = df_position_bruit["bruit_2"].astype(float)

df_position_bruit[df_position_bruit["bruit_3"]==""] = np.nan

df_position_bruit["bruit_3"] = df_position_bruit["bruit_3"].astype(float)

df_position_bruit[df_position_bruit["bruit_4"]==""] = np.nan

df_position_bruit["bruit_4"] = df_position_bruit["bruit_4"].astype(float)

In [51]:
df = df_position_bruit[["bruit","bruit_1","bruit_2","bruit_3","bruit_4"]].groupby("bruit").mean()

In [92]:
df[df.index =='RESIDENCE,APPT']

                 bruit_1   bruit_2  bruit_3  bruit_4
bruit
RESIDENCE,APPT  2.444444  6.309859      NaN      NaN